#!/usr/bin/env bash
# Open or update the rolling "bump the spec pin" PR for a config, when latest
# upstream main flows through the generate pipeline + invariants cleanly. Called
# by .github/workflows/spec-bump-check.yml only on a CLEAN drift (generate +
# invariants both passed against latest). Idempotent: one rolling branch
# (chore/spec-bump-<config>), force-updated in place — re-runs move the same PR
# forward instead of opening duplicates.
#
# The diff is a single file: configs/<config>/spec-pin.json (specRef + content
# hash). generated/ and spec/ are gitignored, so nothing else is committed;
# invariant edits, if any, are left for the human reviewer (CI will show them).
#
# GH_TOKEN must be an App/PAT token with contents:write + pull-requests:write on
# this repo (NOT the built-in GITHUB_TOKEN — PRs it opens don't trigger CI). The
# workflow only invokes this script when such a token was minted.
#
# Required env: GH_TOKEN, CONFIG, LATEST, ISSUE_TITLE, DRIFT_LABEL, N_ADDED,
# N_REMOVED, ADDED, REMOVED. Optional (defaulted): UPSTREAM_REPO, UPSTREAM_BRANCH.
set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN (App/PAT with contents+PR write) required}"
: "${CONFIG:?}" "${LATEST:?}" "${ISSUE_TITLE:?}" "${DRIFT_LABEL:?}"
N_ADDED="${N_ADDED:-0}"
N_REMOVED="${N_REMOVED:-0}"
# Which upstream this config validated against (the workflow sets these per
# matrix leg; default to camunda-oca's for a bare local run).
UPSTREAM_REPO="${UPSTREAM_REPO:-camunda/camunda}"
UPSTREAM_BRANCH="${UPSTREAM_BRANCH:-main}"

# shellcheck source=.github/scripts/spec-bump-common.sh
source "$(dirname "${BASH_SOURCE[0]}")/spec-bump-common.sh"

pin_path="configs/${CONFIG}/spec-pin.json"
branch="$(bump_branch)"
short="${LATEST:0:12}"

# Labels so this PR is distinguishable from a hand-authored one at a glance
# (#473) — created here (best-effort) too, since the early-return path below
# can reach a `gh pr edit` before the later creation calls run.
gh label create "$DRIFT_LABEL" --color BFD4F2 --description "Upstream spec drifted from the pin (spec-bump check)" 2>/dev/null || true
gh label create auto-generated --color ededed --description "Opened by automation, not a human" 2>/dev/null || true

# If a bump PR is already open, leave it alone — it may carry reviewer edits
# (e.g. invariant updates), and force-pushing the rolling branch would clobber
# them. It's still a valid "adopt the bump" PR even if upstream has moved a bit
# further; the next run picks up fresh drift once it's merged or closed. We only
# make sure the tracking issue is closed (the PR supersedes it), and — since an
# existing bump PR could predate this labeling change — self-heal its labels
# too rather than leaving it permanently unlabeled.
existing="$(find_bump_pr)"
if [ -n "$existing" ]; then
  echo "Bump PR #${existing} already open — leaving it as-is (not force-updating)."
  gh pr edit "$existing" --add-label "$DRIFT_LABEL" --add-label auto-generated >/dev/null
  issue="$(find_rolling_issue)"
  if [ -n "$issue" ]; then
    gh issue close "$issue" --comment "Superseded by the open auto-bump PR #${existing}. Closing." >/dev/null
    echo "Closed superseded tracking issue #${issue}."
  fi
  exit 0
fi

# Rewrite the pin via the shared bumper (single source of truth for pin writes):
# it resolves --ref to a 40-char SHA and writes specRef + expectedSpecHash,
# preserving the $comment. The check already bundled this ref to verify it's
# clean; bump-spec-pin re-bundles the same ref (cheap) and writes that same
# validated pin.
npm run bump-spec-pin -- --config "$CONFIG" --ref "$LATEST"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -B "$branch"
git add "$pin_path"
if git diff --cached --quiet; then
  echo "spec-pin.json already at ${short} — nothing to commit."
  exit 0
fi

git commit -m "chore(${CONFIG}): bump spec pin to ${short}

Auto-generated by the spec-bump check: latest ${UPSTREAM_REPO}@${UPSTREAM_BRANCH}
(${LATEST}) flows through the ${CONFIG} generate pipeline + regression invariants
cleanly. Operations added/removed vs the previous pin: +${N_ADDED}/-${N_REMOVED}.

Review the invariant deltas (if CI flags any) before merging." >/dev/null

# Push over the App token (built-in GITHUB_TOKEN's PRs don't trigger CI). Plain
# --force is safe here: we returned early above if a PR was open, so the branch
# is either new or an abandoned one from a previously closed PR (no reviewer
# work to clobber).
#
# actions/checkout persists the built-in GITHUB_TOKEN as an http.extraheader in
# the local git config, and that Authorization header takes precedence over any
# token embedded in the remote URL — so the App token would be ignored and the
# push authenticates as the read-only github-actions[bot] (403 "Permission
# denied"). Drop the persisted header first so the App-token URL below is used.
git config --local --unset-all 'http.https://github.com/.extraheader' 2>/dev/null || true
git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push --force origin "$branch"

# --- Build PR body ----------------------------------------------------------
body_file="$(mktemp)"
{
  echo "Auto-generated by the spec-bump check. Latest \`${UPSTREAM_REPO}@${UPSTREAM_BRANCH}\` (\`${LATEST}\`) flows through the ${CONFIG} generate pipeline **and** regression invariants cleanly, so the pin is safe to adopt."
  echo
  echo "🆕 **Operations added** vs the previous pin (${N_ADDED}):"
  list_or_none "${ADDED:-}"
  echo
  echo "🗑️ **Operations removed** (${N_REMOVED}):"
  list_or_none "${REMOVED:-}"
  echo
  echo "✅ Validated green by the check: [generate + invariants run](${run_url})."
  echo "⚠️ If CI here flags any invariant whose value legitimately changed, update \`configs/${CONFIG}/regression-invariants.test.ts\` in this PR before merging."
  echo
  echo "🤖 Rolling PR — updated in place by each check; do not rename the branch (\`${branch}\`)."
} > "$body_file"

# No open PR for this branch (checked + returned early above), so always create.
title="chore(${CONFIG}): bump spec pin to ${short}"
echo "Opening bump PR."
gh pr create --draft --base main --head "$branch" --title "$title" --body-file "$body_file" \
  --label "$DRIFT_LABEL" --label auto-generated >/dev/null

# Clean up the tracking issue if one is open — the PR supersedes it.
issue="$(find_rolling_issue)"
if [ -n "$issue" ]; then
  gh issue close "$issue" \
    --comment "✅ Latest now flows through cleanly — superseded by the auto-bump PR (branch \`${branch}\`). Closing this tracking issue." >/dev/null
  echo "Closed superseded tracking issue #${issue}."
fi
