#!/usr/bin/env bash
# Open or update the rolling "bump the spec pin" PR for a config, when latest
# upstream main flows through the generate pipeline + invariants cleanly. Called
# by .github/workflows/spec-bump-check.yml only on a CLEAN drift (generate +
# invariants both passed against latest). Idempotent: one rolling branch
# (chore/spec-bump-<config>), force-updated in place — re-runs move the same PR
# forward instead of opening duplicates.
#
# The diff is a single file: configs/<config>/spec-pin.json (specRef + content
# hash). generated/ and spec/ are gitignored, so nothing else is committed;
# invariant edits, if any, are left for the human reviewer (CI will show them).
#
# GH_TOKEN must be an App/PAT token with contents:write + pull-requests:write on
# this repo (NOT the built-in GITHUB_TOKEN — PRs it opens don't trigger CI). The
# workflow only invokes this script when such a token was minted.
#
# Required env: GH_TOKEN, CONFIG, LATEST, ISSUE_TITLE, DRIFT_LABEL, N_ADDED,
# N_REMOVED, ADDED, REMOVED. Optional (defaulted): UPSTREAM_REPO, UPSTREAM_BRANCH.
set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN (App/PAT with contents+PR write) required}"
: "${CONFIG:?}" "${LATEST:?}" "${ISSUE_TITLE:?}" "${DRIFT_LABEL:?}"
N_ADDED="${N_ADDED:-0}"
N_REMOVED="${N_REMOVED:-0}"
# Which upstream this config validated against (the workflow sets these per
# matrix leg; default to camunda-oca's for a bare local run).
UPSTREAM_REPO="${UPSTREAM_REPO:-camunda/camunda}"
UPSTREAM_BRANCH="${UPSTREAM_BRANCH:-main}"

# shellcheck source=.github/scripts/spec-bump-common.sh
source "$(dirname "${BASH_SOURCE[0]}")/spec-bump-common.sh"

pin_path="configs/${CONFIG}/spec-pin.json"
branch="$(bump_branch)"
short="${LATEST:0:12}"

# Labels so this PR is distinguishable from a hand-authored one at a glance
# (#473) — created here (best-effort) too, since the early-return path below
# can reach a `gh pr edit` before the later creation calls run.
gh label create "$DRIFT_LABEL" --color BFD4F2 --description "Upstream spec drifted from the pin (spec-bump check)" 2>/dev/null || true
gh label create auto-generated --color ededed --description "Opened by automation, not a human" 2>/dev/null || true

# If a bump PR is already open, leave it alone — it may carry reviewer edits
# (e.g. invariant updates), and force-pushing the rolling branch would clobber
# them. It's still a valid "adopt the bump" PR even if upstream has moved a bit
# further; the next run picks up fresh drift once it's merged or closed. We only
# make sure the tracking issue is closed (the PR supersedes it), and — since an
# existing bump PR could predate this labeling change — self-heal its labels
# too rather than leaving it permanently unlabeled.
existing="$(find_bump_pr)"
if [ -n "$existing" ]; then
  echo "Bump PR #${existing} already open — leaving it as-is (not force-updating)."
  # Best-effort: a transient API error here must not prevent closing the
  # superseded tracking issue below (labeling is an auxiliary self-heal, the
  # issue-close is the actual point of this path).
  gh pr edit "$existing" --add-label "$DRIFT_LABEL" --add-label auto-generated >/dev/null || true
  issue="$(find_rolling_issue)"
  if [ -n "$issue" ]; then
    gh issue close "$issue" --comment "Superseded by the open auto-bump PR #${existing}. Closing." >/dev/null
    echo "Closed superseded tracking issue #${issue}."
  fi
  exit 0
fi

# Rewrite the pin via the shared bumper (single source of truth for pin writes):
# it resolves --ref to a 40-char SHA and writes specRef + expectedSpecHash,
# preserving the $comment. The check already bundled this ref to verify it's
# clean; bump-spec-pin re-bundles the same ref (cheap) and writes that same
# validated pin.
npm run bump-spec-pin -- --config "$CONFIG" --ref "$LATEST"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -B "$branch"
git add "$pin_path"
if git diff --cached --quiet; then
  echo "spec-pin.json already at ${short} — nothing to commit."
  exit 0
fi

git commit -m "chore(${CONFIG}): bump spec pin to ${short}

Auto-generated by the spec-bump check: latest ${UPSTREAM_REPO}@${UPSTREAM_BRANCH}
(${LATEST}) flows through the ${CONFIG} generate pipeline + regression invariants
cleanly. Operations added/removed vs the previous pin: +${N_ADDED}/-${N_REMOVED}.

Review the invariant deltas (if CI flags any) before merging." >/dev/null

# Push over the App token (built-in GITHUB_TOKEN's PRs don't trigger CI). Plain
# --force is safe here: we returned early above if a PR was open, so the branch
# is either new or an abandoned one from a previously closed PR (no reviewer
# work to clobber).
#
# actions/checkout persists the built-in GITHUB_TOKEN as an http.extraheader in
# the local git config, and that Authorization header takes precedence over any
# token embedded in the remote URL — so the App token would be ignored and the
# push authenticates as the read-only github-actions[bot] (403 "Permission
# denied"). Drop the persisted header first so the App-token URL below is used.
git config --local --unset-all 'http.https://github.com/.extraheader' 2>/dev/null || true
git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push --force origin "$branch"

# --- Build PR body ----------------------------------------------------------
body_file="$(mktemp)"
{
  echo "Auto-generated by the spec-bump check. Latest \`${UPSTREAM_REPO}@${UPSTREAM_BRANCH}\` (\`${LATEST}\`) flows through the ${CONFIG} generate pipeline **and** regression invariants cleanly, so the pin is safe to adopt."
  echo
  echo "🆕 **Operations added** vs the previous pin (${N_ADDED}):"
  list_or_none "${ADDED:-}"
  echo
  echo "🗑️ **Operations removed** (${N_REMOVED}):"
  list_or_none "${REMOVED:-}"
  echo
  # Only shown when there's something to show (#492) — the common case is no
  # field-level change, and an empty section every PR would just be clutter.
  # Newly-required request properties never reach here: they gate this PR
  # path entirely and route to the tracking issue instead (see fielddiff's
  # has_newly_required check in the workflow).
  if [ "${N_FIELD_ADDED:-0}" != "0" ] || [ "${N_FIELD_REMOVED:-0}" != "0" ]; then
    echo "🔬 **Field-level schema changes** within existing operations (informational — additive/optional changes need no generator update; see #492):"
    echo "- Added (${N_FIELD_ADDED:-0}):"
    list_or_none "${FIELD_ADDED:-}"
    echo "- Removed (${N_FIELD_REMOVED:-0}):"
    list_or_none "${FIELD_REMOVED:-}"
    echo
  fi
  echo "✅ Validated green by the check: [generate + invariants run](${run_url})."
  echo "⚠️ If CI here flags any invariant whose value legitimately changed, update \`configs/${CONFIG}/regression-invariants.test.ts\` in this PR before merging."
  echo
  echo "🤖 Rolling PR — updated in place by each check; do not rename the branch (\`${branch}\`)."
} > "$body_file"

# No open PR for this branch (checked + returned early above), so always create.
title="chore(${CONFIG}): bump spec pin to ${short}"
echo "Opening bump PR."
gh pr create --draft --base main --head "$branch" --title "$title" --body-file "$body_file" \
  --label "$DRIFT_LABEL" --label auto-generated >/dev/null

# Clean up the tracking issue if one is open — the PR supersedes it.
issue="$(find_rolling_issue)"
if [ -n "$issue" ]; then
  gh issue close "$issue" \
    --comment "✅ Latest now flows through cleanly — superseded by the auto-bump PR (branch \`${branch}\`). Closing this tracking issue." >/dev/null
  echo "Closed superseded tracking issue #${issue}."
fi

# --- Hub only: trigger on-demand validation against a live Hub -------------
# Mirrors the same pattern the nightly triage agent uses for its own fix/
# suppress PRs (see "Trigger on-demand validation..." in
# triage-camunda-hub-nightly.yml): ci.yml's hub-invariants job already runs
# automatically on this PR, but it never starts a live Hub (static
# invariants against the pinned spec only), so it can't confirm the new pin
# actually works end-to-end. hub-ondemand-test.yml does exactly that but is
# workflow_dispatch-only — nothing triggers it automatically otherwise.
#
# camunda-oca has no equivalent live-instance workflow, hence IS_PRIVATE-only.
#
# Unlike the triage agent's PRs (LLM-authored from untrusted nightly-report
# content, hence that workflow's extra ".github/** touched?" guard before
# dispatching with production secrets), this diff is fully deterministic:
# this script staged exactly configs/${CONFIG}/spec-pin.json above — nothing
# else — via `git add "$pin_path"` + the earlier `git diff --cached --quiet`
# early-return. There's no agent-authored content that could smuggle in a
# .github/** change, so that extra guard doesn't apply here.
if [ "${IS_PRIVATE:-}" = "true" ]; then
  pr_num="$(find_bump_pr)"
  if [ -z "$pr_num" ]; then
    echo "::warning::Could not resolve the bump PR number for validation dispatch — skipping."
  else
    # Captured BEFORE dispatch: this is the ROLLING bump branch (force-pushed
    # and reused across every bump cycle, unlike the triage agent's one-shot
    # per-PR branches this polling logic is adapted from) — an OLD
    # hub-ondemand-test.yml run from a previous, unrelated bump cycle can
    # already exist for this exact branch name. Without a time filter,
    # `gh run list --limit 1` could return that stale run before the new
    # dispatch is even indexed (workflow_run creation isn't synchronous with
    # the dispatch call), commenting a link to the wrong run entirely. A 30s
    # buffer tolerates clock skew between this runner and GitHub's own
    # timestamps, same as trigger-api-test-generator.yml's identical "reject
    # anything older than our own action" guard.
    dispatched_at="$(date -u -d '30 seconds ago' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
      || date -u -v-30S +%Y-%m-%dT%H:%M:%SZ)"

    if ! gh workflow run hub-ondemand-test.yml --repo camunda/api-test-generator --ref "$branch"; then
      echo "::warning::Could not dispatch hub-ondemand-test.yml for the bump PR."
      gh pr comment "$pr_num" --repo camunda/api-test-generator \
        --body ":warning: Could not auto-dispatch on-demand validation (\`hub-ondemand-test.yml\`) for this PR — please trigger it manually against this branch before merging (it starts a live Hub and runs the real suite; \`hub-invariants\` on this PR only checks static invariants against the pinned spec, not a live run)." \
        2>/dev/null || true
    else
      # Poll briefly for the run this dispatch just created, filtering out
      # anything older than dispatched_at (see above) — a handful of
      # candidates, not just the newest one, since a stale run could easily
      # sort first if our new one is still being indexed.
      run_url=""
      for _ in 1 2 3 4 5 6 7 8 9 10; do
        sleep 3
        # gh's own --jq/-q takes exactly one expression, no --arg passthrough
        # (confirmed against `gh run list --help`) — piped into a real jq
        # instead, which does support it.
        # shellcheck disable=SC2016  # $since is a jq --arg var, not shell
        run_id=$(gh run list --repo camunda/api-test-generator --workflow=hub-ondemand-test.yml \
          --branch "$branch" --event workflow_dispatch --limit 5 --json databaseId,createdAt \
          2>/dev/null | jq -r --arg since "$dispatched_at" \
          '[.[] | select(.createdAt >= $since)] | sort_by(.createdAt) | .[0].databaseId // empty' \
          2>/dev/null || true)
        if [ -n "$run_id" ]; then
          run_url="https://github.com/camunda/api-test-generator/actions/runs/${run_id}"
          break
        fi
      done
      # shellcheck disable=SC2016  # literal backticks for markdown, no expansion wanted
      note_body=$(if [ -n "$run_url" ]; then
        printf '🔎 **On-demand validation**: [hub-ondemand-test run](%s) — dispatched automatically. This confirms the new pin actually passes against a live Hub, not just static invariants (which is all `hub-invariants` on this PR checks).' "$run_url"
      else
        printf '⚠️ Dispatched `hub-ondemand-test.yml` for validation but could not resolve the run URL within the poll window — check the Actions tab for branch `%s`.' "$branch"
      fi)
      gh pr comment "$pr_num" --repo camunda/api-test-generator --body "$note_body" 2>/dev/null \
        || echo "::warning::Could not comment validation link on #${pr_num}"
    fi
  fi
fi
