#!/usr/bin/env bash
# Open or update the rolling "bump the spec pin" PR for a config, when latest
# upstream main flows through the generate pipeline + invariants cleanly. Called
# by .github/workflows/spec-bump-dryrun.yml only on a CLEAN drift (generate +
# invariants both passed against latest). Idempotent: one rolling branch
# (chore/spec-bump-<config>), force-updated in place — re-runs move the same PR
# forward instead of opening duplicates.
#
# The diff is a single file: configs/<config>/spec-pin.json (specRef + content
# hash). generated/ and spec/ are gitignored, so nothing else is committed;
# invariant edits, if any, are left for the human reviewer (CI will show them).
#
# GH_TOKEN must be an App/PAT token with contents:write + pull-requests:write on
# this repo (NOT the built-in GITHUB_TOKEN — PRs it opens don't trigger CI). The
# workflow only invokes this script when such a token was minted.
#
# Required env: GH_TOKEN, CONFIG, LATEST, N_ADDED, N_REMOVED, ADDED, REMOVED.
set -euo pipefail

: "${GH_TOKEN:?GH_TOKEN (App/PAT with contents+PR write) required}"
: "${CONFIG:?}" "${LATEST:?}" "${ISSUE_TITLE:?}"
N_ADDED="${N_ADDED:-0}"
N_REMOVED="${N_REMOVED:-0}"

pin_path="configs/${CONFIG}/spec-pin.json"
meta_path="spec/${CONFIG}/bundled/spec-metadata.json"
branch="chore/spec-bump-${CONFIG}"
short="${LATEST:0:12}"
run_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

# If a bump PR is already open, leave it alone — it may carry reviewer edits
# (e.g. invariant updates), and force-pushing the rolling branch would clobber
# them. It's still a valid "adopt the bump" PR even if upstream has moved a bit
# further; the next run picks up fresh drift once it's merged or closed. We only
# make sure the tracking issue is closed (the PR supersedes it).
existing="$(gh pr list --head "$branch" --state open --json number --jq '.[0].number // empty')"
if [ -n "$existing" ]; then
  echo "Bump PR #${existing} already open — leaving it as-is (not force-updating)."
  issue="$(gh issue list --state open --search "in:title \"${ISSUE_TITLE}\"" \
    --json number,title --jq ".[] | select(.title == \"${ISSUE_TITLE}\") | .number" | head -1)"
  if [ -n "$issue" ]; then
    gh issue close "$issue" --comment "Superseded by the open auto-bump PR #${existing}. Closing." >/dev/null
    echo "Closed superseded tracking issue #${issue}."
  fi
  exit 0
fi

new_hash="$(node -e "console.log(JSON.parse(require('fs').readFileSync('${meta_path}','utf8')).specHash)")"

# Rewrite the pin, preserving key order + the $comment.
node -e '
  const fs = require("fs");
  const [p, ref, hash] = process.argv.slice(1);
  const d = JSON.parse(fs.readFileSync(p, "utf8"));
  d.specRef = ref;
  d.expectedSpecHash = hash;
  fs.writeFileSync(p, JSON.stringify(d, null, 2) + "\n");
' "$pin_path" "$LATEST" "$new_hash"

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git checkout -B "$branch"
git add "$pin_path"
if git diff --cached --quiet; then
  echo "spec-pin.json already at ${short} — nothing to commit."
  exit 0
fi

git commit -m "chore(${CONFIG}): bump spec pin to ${short}

Auto-generated by the spec-bump dry-run (#387): latest camunda/camunda@main
(${LATEST}) flows through the generate pipeline + regression invariants
cleanly. Operations added/removed vs the previous pin: +${N_ADDED}/-${N_REMOVED}.

Review the invariant deltas (if CI flags any) before merging." >/dev/null

# Push over the App token (built-in GITHUB_TOKEN's PRs don't trigger CI). Plain
# --force is safe here: we returned early above if a PR was open, so the branch
# is either new or an abandoned one from a previously closed PR (no reviewer
# work to clobber).
git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push --force origin "$branch"

# --- Build PR body ----------------------------------------------------------
list_or_none() {
  local lines
  lines=$(printf '%s\n' "$1" | grep -E '.' || true)
  if [ -z "$lines" ]; then echo "_(none)_"; return; fi
  # shellcheck disable=SC2016  # literal backticks for markdown, no expansion wanted
  printf '%s\n' "$lines" | head -50 | sed 's/^/- `/;s/$/`/' || true
}
body_file="$(mktemp)"
{
  echo "Auto-generated by the spec-bump dry-run (#387). Latest \`camunda/camunda@main\` (\`${LATEST}\`) flows through the ${CONFIG} generate pipeline **and** regression invariants cleanly, so the pin is safe to adopt."
  echo
  echo "🆕 **Operations added** vs the previous pin (${N_ADDED}):"
  list_or_none "${ADDED:-}"
  echo
  echo "🗑️ **Operations removed** (${N_REMOVED}):"
  list_or_none "${REMOVED:-}"
  echo
  echo "✅ Validated green by the dry-run: [generate + invariants run](${run_url})."
  echo "⚠️ If CI here flags any invariant whose value legitimately changed, update \`configs/${CONFIG}/regression-invariants.test.ts\` in this PR before merging."
  echo
  echo "🤖 Rolling PR — updated in place by each dry-run; do not rename the branch (\`${branch}\`)."
} > "$body_file"

# No open PR for this branch (checked + returned early above), so always create.
title="chore(${CONFIG}): bump spec pin to ${short}"
echo "Opening bump PR."
gh pr create --draft --base main --head "$branch" --title "$title" --body-file "$body_file" >/dev/null

# Clean up the tracking issue if one is open — the PR supersedes it.
issue="$(gh issue list --state open --search "in:title \"${ISSUE_TITLE}\"" \
  --json number,title --jq ".[] | select(.title == \"${ISSUE_TITLE}\") | .number" | head -1)"
if [ -n "$issue" ]; then
  gh issue close "$issue" \
    --comment "✅ Latest now flows through cleanly — superseded by the auto-bump PR (branch \`${branch}\`). Closing this tracking issue." >/dev/null
  echo "Closed superseded tracking issue #${issue}."
fi
