import { normalizeKind } from '../model/types.js';

export interface KindCoverage {
  /** Kinds that should have a scenario for the operation (aliases resolved, present kinds included). */
  applicable: Set<string>;
  /** Kinds that do have a scenario for the operation (aliases resolved). */
  present: Set<string>;
  /** Applicable kinds with no scenario, sorted. */
  missingApplicable: string[];
}

/**
 * The per-operation coverage of scenario kinds that COVERAGE.json reports.
 *
 * Both sides go through `normalizeKind`: a `body-top-type-mismatch` scenario is counted as
 * `type-mismatch`, so the applicable set has to say `type-mismatch` too. If only the present side
 * were normalized, the aliased kind would be reported as missing for every operation that takes it
 * whatever was generated. Present kinds are also added to the applicable set so the percentage
 * cannot exceed 100.
 */
export function computeKindCoverage(
  applicableKinds: Iterable<string>,
  presentKinds: Iterable<string>,
): KindCoverage {
  const present = new Set<string>();
  for (const kind of presentKinds) present.add(normalizeKind(kind));
  const applicable = new Set<string>();
  for (const kind of applicableKinds) applicable.add(normalizeKind(kind));
  for (const kind of present) applicable.add(kind);
  const missingApplicable = Array.from(applicable)
    .filter((kind) => !present.has(kind))
    .sort();
  return { applicable, present, missingApplicable };
}

export interface OperationWithoutScenarios {
  operationId: string;
  applicableKindCount: number;
  presentKindCount: number;
  missingApplicableKinds: string[];
}

/**
 * Operations that ended up with no scenario at all (a scoped exclusion can remove every one),
 * with the kinds that apply to them. COVERAGE.json's `operations` list is built from the scenarios
 * that survive, so such an operation is absent from it; without this list a consumer cannot tell
 * "everything was excluded on purpose" from "nothing was generated by mistake".
 */
export function listOperationsWithoutScenarios(
  coverageByOperation: Readonly<
    Record<string, { applicable: ReadonlySet<string>; missingApplicable: readonly string[] }>
  >,
  operationsWithScenarios: ReadonlySet<string>,
): OperationWithoutScenarios[] {
  return Object.entries(coverageByOperation)
    .filter(([operationId]) => !operationsWithScenarios.has(operationId))
    .map(([operationId, coverage]) => ({
      operationId,
      applicableKindCount: coverage.applicable.size,
      presentKindCount: 0,
      missingApplicableKinds: [...coverage.missingApplicable],
    }))
    .sort((a, b) => a.operationId.localeCompare(b.operationId));
}

/** What the coverage calculation needs of a scenario: which operation it belongs to and its kind. */
export interface ScenarioKindRef {
  operationId: string;
  type: string;
}

/**
 * For each operation, the kinds that a whole-kind exclusion removed entirely: the kind existed before
 * the filter, has no scenario left after it, and a rule with no target or constraint scope names it
 * (kind names as COVERAGE.json reports them).
 *
 * A rule scoped to some targets is deliberately never counted. It leaves the other targets of the
 * kind running, and the generator cannot tell "the scoped rule removed every scenario" from "a sibling
 * target that should remain stopped being generated", so holding the kind could hide that regression.
 * Such a kind shows as a gap instead, which is the safe way to be wrong. A kind that was never
 * generated is not held either.
 */
export function kindsRemovedEntirely(
  before: readonly ScenarioKindRef[],
  after: readonly ScenarioKindRef[],
  wholeKindExclusions: ReadonlyMap<string, ReadonlySet<string>>,
): Record<string, string[]> {
  const kindsByOperation = (scenarios: readonly ScenarioKindRef[]) => {
    const result = new Map<string, Set<string>>();
    for (const s of scenarios) {
      const kinds = result.get(s.operationId) ?? new Set<string>();
      kinds.add(normalizeKind(s.type));
      result.set(s.operationId, kinds);
    }
    return result;
  };
  const kindsBefore = kindsByOperation(before);
  const kindsAfter = kindsByOperation(after);
  const removed: Record<string, string[]> = {};
  for (const [operationId, kinds] of kindsBefore) {
    const excludedWhole = wholeKindExclusions.get(operationId);
    if (!excludedWhole) continue;
    const gone = [...kinds]
      .filter((kind) => excludedWhole.has(kind) && !kindsAfter.get(operationId)?.has(kind))
      .sort();
    if (gone.length > 0) removed[operationId] = gone;
  }
  return removed;
}
