// Reads the unified ontology bundle (generated by `npm run export:ontology`)
// and the operation-dependency graph (generated by `npm run extract-graph`),
// then emits:
//
//   generated/<cfg>/viz/tbox.dot       — TBox class diagram (Graphviz)
//   generated/<cfg>/viz/abox.dot       — ABox instance graph (Graphviz)
//   generated/<cfg>/viz/operations.dot — full operation-dependency graph (Graphviz)
//   generated/<cfg>/viz/tbox.mmd       — TBox Mermaid diagram
//   generated/<cfg>/viz/abox.mmd       — ABox Mermaid diagram
//
// Committed snapshots kept in sync with the current ABox:
//   ontology/diagrams/tbox.mmd
//   ontology/diagrams/abox.mmd
//
// With --check: exits non-zero if the committed .mmd files drift from what
// the script would generate (mirrors sync-readme-snippets pattern).
//
// With `dot` on PATH: each .dot is piped through `dot -Tsvg` to produce a
// matching .svg. If dot is missing, .dot files are emitted only.
//
// Run via: npm run viz:ontology
//           npm run viz:ontology -- --check

import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  getActiveConfigName,
  getGeneratedDir,
  getGraphDir,
} from '../path-analyser/src/configResolver.ts';
import { buildBundle, getBundlePath } from './export-ontology.ts';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// ---------------------------------------------------------------------------
// Typed helpers for ABox / graph data extracted from the bundle
// ---------------------------------------------------------------------------

interface ABoxEdge {
  name: string;
  endpoints: { from: string; to: string };
  establishedBy: string;
  revokedBy: string;
  observableVia: string;
}

interface ABoxEntityKind {
  name: string;
  shape: string;
}

interface SerializedOperation {
  operationId: string;
  tags?: string[];
}

interface SerializedDependencyEdge {
  sourceOperationId: string;
  targetOperationId: string;
  semanticType: string;
}

interface SerializedGraph {
  operations: SerializedOperation[];
  edges: SerializedDependencyEdge[];
}

// ---------------------------------------------------------------------------
// Guards
// ---------------------------------------------------------------------------

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v);
}

function isABoxEdge(v: unknown): v is ABoxEdge {
  if (!isRecord(v)) return false;
  const endpoints = v.endpoints;
  return (
    typeof v.name === 'string' &&
    isRecord(endpoints) &&
    typeof endpoints.from === 'string' &&
    typeof endpoints.to === 'string' &&
    typeof v.establishedBy === 'string' &&
    typeof v.revokedBy === 'string' &&
    typeof v.observableVia === 'string'
  );
}

function isABoxEntityKind(v: unknown): v is ABoxEntityKind {
  return isRecord(v) && typeof v.name === 'string' && typeof v.shape === 'string';
}

function isSerializedGraph(v: unknown): v is SerializedGraph {
  return isRecord(v) && Array.isArray(v.operations) && Array.isArray(v.edges);
}

// ---------------------------------------------------------------------------
// DOT / Mermaid ID helpers
// ---------------------------------------------------------------------------

/** Escape a string for use as a DOT node ID (no hyphens, camelCase). */
function dotId(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}

/** Escape a string for use inside a DOT label (double-quoted). */
function dotLabel(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

/** Escape a string for use as a Mermaid node ID (alphanumeric). */
function mmdId(name: string): string {
  return name.replace(/[^A-Za-z0-9]/g, '_');
}

// ---------------------------------------------------------------------------
// TBox emitters
// ---------------------------------------------------------------------------

// Static TBox cross-reference topology derived from domain knowledge:
// the JSON Schemas do not carry explicit $ref cross-references between
// slices; the dependencies are encoded as plain string values in the ABox.
const TBOX_EDGES: { from: string; to: string; label: string }[] = [
  { from: 'edge', to: 'entity_kinds', label: 'endpoints.from/to' },
  { from: 'edge', to: 'semantics', label: 'identifiedBy' },
  { from: 'artifact_kinds', to: 'semantics', label: 'producesSemantics' },
  { from: 'runtime_states', to: 'entity_kinds', label: 'operationRequirements' },
  { from: 'scenario_template', to: 'edge', label: 'appliesTo (edge)' },
  { from: 'scenario_template', to: 'entity_kinds', label: 'appliesTo (entity)' },
];

const TBOX_NODES: { id: string; label: string; file: string }[] = [
  { id: 'edge', label: 'Edge', file: 'edge.schema.json' },
  { id: 'entity_kinds', label: 'EntityKind', file: 'entity-kinds.schema.json' },
  { id: 'artifact_kinds', label: 'ArtifactKind', file: 'artifact-kinds.schema.json' },
  { id: 'runtime_states', label: 'RuntimeState', file: 'runtime-states.schema.json' },
  { id: 'semantics', label: 'SemanticType', file: 'semantics.schema.json' },
  {
    id: 'global_context_seeds',
    label: 'GlobalContextSeed',
    file: 'global-context-seeds.schema.json',
  },
  { id: 'scenario_template', label: 'ScenarioTemplate', file: 'scenario-template.schema.json' },
];

export function emitTboxDot(configName: string): string {
  const lines: string[] = [
    'digraph TBox {',
    `  graph [label="api-test-generator Ontology TBox (${configName})\\n7 JSON Schema slices", labelloc=t, fontname=Helvetica, bgcolor=white];`,
    '  node [shape=box, style="filled,rounded", fillcolor="#DAE8FC", color="#6C8EBF", fontname=Helvetica];',
    '  edge [fontname=Helvetica, fontsize=10, color="#444444"];',
    '',
  ];
  for (const { id, label, file } of TBOX_NODES) {
    lines.push(`  ${id} [label="${dotLabel(label)}\\n${dotLabel(file)}"];`);
  }
  lines.push('');
  for (const { from, to, label } of TBOX_EDGES) {
    lines.push(`  ${from} -> ${to} [label="${dotLabel(label)}"];`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

export function emitTboxMmd(configName: string): string {
  const lines: string[] = [
    `%% api-test-generator Ontology TBox (${configName}) — 7 JSON Schema slices`,
    'graph LR',
  ];
  for (const { id, label, file } of TBOX_NODES) {
    lines.push(`  ${id}["**${label}**<br/>${file}"]`);
  }
  lines.push('');
  for (const { from, to, label } of TBOX_EDGES) {
    lines.push(`  ${from} -->|"${label}"| ${to}`);
  }
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// ABox emitters (derive from bundle data)
// ---------------------------------------------------------------------------

function extractABoxEdges(bundle: ReturnType<typeof buildBundle>): ABoxEdge[] {
  const raw = bundle.abox.edges;
  if (!isRecord(raw)) return [];
  const arr = raw.edges;
  if (!Array.isArray(arr)) return [];
  return arr.filter(isABoxEdge);
}

function extractABoxEntityKinds(bundle: ReturnType<typeof buildBundle>): ABoxEntityKind[] {
  const raw = bundle.abox.entityKinds;
  if (!isRecord(raw)) return [];
  const arr = raw.kinds;
  if (!Array.isArray(arr)) return [];
  return arr.filter(isABoxEntityKind);
}

export function emitAboxDot(bundle: ReturnType<typeof buildBundle>): string {
  const kinds = extractABoxEntityKinds(bundle);
  const edges = extractABoxEdges(bundle);

  const lines: string[] = [
    'digraph ABox {',
    `  graph [label="api-test-generator ABox (${bundle.config})\\nEntity kinds and membership edges", labelloc=t, fontname=Helvetica, bgcolor=white];`,
    '  node [shape=ellipse, style=filled, fillcolor="#D5E8D4", color="#82B366", fontname=Helvetica, fontsize=11];',
    '  edge [fontname=Helvetica, fontsize=9, color="#444444"];',
    '',
  ];

  const kindSet = new Set<string>();
  for (const k of kinds) {
    const id = dotId(k.name);
    const shapeAttr = k.shape === 'external-entity' ? ', fillcolor="#FFE6CC", color="#D6B656"' : '';
    lines.push(`  ${id} [label="${dotLabel(k.name)}"${shapeAttr}];`);
    kindSet.add(k.name);
  }
  // Add any endpoint kinds referenced in edges but not in entity-kinds
  for (const e of edges) {
    for (const n of [e.endpoints.from, e.endpoints.to]) {
      if (!kindSet.has(n)) {
        lines.push(`  ${dotId(n)} [label="${dotLabel(n)}", fillcolor="#FFE6CC", color="#D6B656"];`);
        kindSet.add(n);
      }
    }
  }

  lines.push('');
  for (const e of edges) {
    const fromId = dotId(e.endpoints.from);
    const toId = dotId(e.endpoints.to);
    // Join with a real newline; dotLabel() converts \n → the DOT \n escape.
    // Joining with the literal '\n' two-char sequence would be double-escaped
    // by dotLabel() into '\\n' and rendered verbatim in the SVG.
    const lbl = [e.name, `+${e.establishedBy}`, `−${e.revokedBy}`, `obs: ${e.observableVia}`].join(
      '\n',
    );
    lines.push(`  ${fromId} -> ${toId} [label="${dotLabel(lbl)}"];`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

export function emitAboxMmd(bundle: ReturnType<typeof buildBundle>): string {
  const kinds = extractABoxEntityKinds(bundle);
  const edges = extractABoxEdges(bundle);

  const lines: string[] = [
    `%% api-test-generator ABox (${bundle.config}) — entity kinds and membership edges`,
    'graph LR',
  ];

  const kindSet = new Set<string>();
  for (const k of kinds) {
    const id = mmdId(k.name);
    const shape = k.shape === 'runtime-entity' ? `{${k.name}}` : `(${k.name})`;
    lines.push(`  ${id}${shape}`);
    kindSet.add(k.name);
  }
  for (const e of edges) {
    for (const n of [e.endpoints.from, e.endpoints.to]) {
      if (!kindSet.has(n)) {
        lines.push(`  ${mmdId(n)}["${n}"]`);
        kindSet.add(n);
      }
    }
  }

  lines.push('');
  for (const e of edges) {
    const fromId = mmdId(e.endpoints.from);
    const toId = mmdId(e.endpoints.to);
    lines.push(`  ${fromId} -->|"${e.name}"| ${toId}`);
  }
  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Operations DOT emitter (requires the dependency graph)
// ---------------------------------------------------------------------------

export function emitOperationsDot(graph: SerializedGraph, configName: string): string {
  // Group operations by first tag (use 'untagged' as fallback).
  const byTag = new Map<string, SerializedOperation[]>();
  for (const op of graph.operations) {
    const tag = op.tags?.[0] ?? 'untagged';
    let bucket = byTag.get(tag);
    if (!bucket) {
      bucket = [];
      byTag.set(tag, bucket);
    }
    bucket.push(op);
  }

  const lines: string[] = [
    'digraph Operations {',
    `  graph [label="api-test-generator Operation Dependency Graph (${configName})\\n${graph.operations.length} operations · ${graph.edges.length} dependencies", labelloc=t, fontname=Helvetica, bgcolor=white, rankdir=LR];`,
    '  node [shape=box, style="filled,rounded", fillcolor="#FFF2CC", color="#D6B656", fontname=Helvetica, fontsize=9];',
    '  edge [fontname=Helvetica, fontsize=8, color="#888888", arrowsize=0.7];',
    '',
  ];

  let clusterIdx = 0;
  for (const [tag, ops] of [...byTag.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  subgraph cluster_${clusterIdx++} {`);
    lines.push(`    label="${dotLabel(tag)}";`);
    lines.push('    style=filled;');
    lines.push('    fillcolor="#FAFAFA";');
    for (const op of ops) {
      lines.push(`    ${dotId(op.operationId)} [label="${dotLabel(op.operationId)}"];`);
    }
    lines.push('  }');
    lines.push('');
  }

  // Deduplicate edges (same source+target+semantic may appear multiple times).
  const seen = new Set<string>();
  for (const e of graph.edges) {
    const key = `${e.sourceOperationId}→${e.targetOperationId}:${e.semanticType}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const src = dotId(e.sourceOperationId);
    const tgt = dotId(e.targetOperationId);
    lines.push(`  ${src} -> ${tgt} [label="${dotLabel(e.semanticType)}"];`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// SVG helper (optional — requires `dot` on PATH)
// ---------------------------------------------------------------------------

function renderSvg(dotSrc: string, svgPath: string): void {
  try {
    const svg = execSync('dot -Tsvg', {
      input: dotSrc,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    writeFileSync(svgPath, svg, 'utf8');
    process.stdout.write(`wrote ${svgPath}\n`);
  } catch {
    // dot is not available; the .dot file was already written.
    process.stdout.write(
      "  (dot not available; install graphviz and re-run 'npm run viz:ontology' for SVGs)\n",
    );
  }
}

// ---------------------------------------------------------------------------
// README transclusion
//
// `ontology/README.md` carries inline Mermaid snapshots for the smaller
// (TBox + ABox) graphs so the rendered README on GitHub shows the
// diagrams directly. Each block is wrapped with HTML-comment markers
// of the form:
//
//   <!-- generated-from: ontology/diagrams/<file>.mmd -->
//   ```mermaid
//   ...current contents of <file>...
//   ```
//   <!-- /generated-from -->
//
// This function rewrites every marker-delimited block in the README so
// the inline copy stays byte-identical with the committed `.mmd` file.
// In `--check` mode it exits non-zero if the README would change. The
// same auto-refresh workflow that keeps `ontology/diagrams/*.mmd` in
// sync after merges also covers the README via this transclusion.
// ---------------------------------------------------------------------------

const README_BLOCK_RE =
  /<!-- generated-from: (ontology\/diagrams\/[\w.-]+\.mmd) -->\n```mermaid\n[\s\S]*?\n```\n<!-- \/generated-from -->/g;

function buildReadmeBlock(relPath: string, content: string): string {
  // The committed .mmd files end with a trailing newline; strip it so
  // the rebuilt block has exactly one newline before the closing fence.
  const body = content.endsWith('\n') ? content.slice(0, -1) : content;
  return `<!-- generated-from: ${relPath} -->\n\`\`\`mermaid\n${body}\n\`\`\`\n<!-- /generated-from -->`;
}

function syncReadme(check: boolean): void {
  const readmePath = join(REPO_ROOT, 'ontology', 'README.md');
  if (!existsSync(readmePath)) return;
  const original = readFileSync(readmePath, 'utf8');

  let missingSource = false;
  const updated = original.replace(README_BLOCK_RE, (_match, relPath: string) => {
    const absPath = join(REPO_ROOT, relPath);
    if (!existsSync(absPath)) {
      process.stderr.write(`README references missing diagram source: ${relPath}\n`);
      missingSource = true;
      return _match;
    }
    return buildReadmeBlock(relPath, readFileSync(absPath, 'utf8'));
  });
  if (missingSource) process.exit(1);

  if (check) {
    if (updated !== original) {
      process.stderr.write(
        'ontology/README.md transcluded Mermaid blocks are out of date. Run `npm run viz:ontology` to update them.\n',
      );
      process.exit(1);
    }
    process.stdout.write('ontology/README.md transcluded blocks are up to date.\n');
    return;
  }
  if (updated !== original) {
    writeFileSync(readmePath, updated, 'utf8');
    process.stdout.write(`wrote ${readmePath} (transcluded diagram blocks)\n`);
  }
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const check = process.argv.includes('--check');

  // Load (or build) the bundle.
  const bundleFilePath = getBundlePath(REPO_ROOT);
  let bundle: ReturnType<typeof buildBundle>;
  if (existsSync(bundleFilePath)) {
    // biome-ignore lint/plugin: runtime contract boundary for parsed pipeline JSON
    bundle = JSON.parse(readFileSync(bundleFilePath, 'utf8')) as ReturnType<typeof buildBundle>;
  } else {
    process.stdout.write('Bundle not found; building from ABox files…\n');
    bundle = buildBundle();
  }

  const configName = getActiveConfigName(REPO_ROOT);
  const vizDir = join(getGeneratedDir(REPO_ROOT), 'viz');
  const diagramsDir = join(REPO_ROOT, 'ontology', 'diagrams');
  mkdirSync(vizDir, { recursive: true });
  mkdirSync(diagramsDir, { recursive: true });

  // ------------------------------------------------------------------
  // TBox
  // ------------------------------------------------------------------
  const tboxDot = emitTboxDot(configName);
  const tboxMmd = emitTboxMmd(configName);

  if (check) {
    const committedTbox = existsSync(join(diagramsDir, 'tbox.mmd'))
      ? readFileSync(join(diagramsDir, 'tbox.mmd'), 'utf8')
      : null;
    if (committedTbox !== tboxMmd) {
      process.stderr.write(
        'ontology/diagrams/tbox.mmd is out of date. Run `npm run viz:ontology` to update it.\n',
      );
      process.exit(1);
    }
    process.stdout.write('ontology/diagrams/tbox.mmd is up to date.\n');
  } else {
    const tboxDotPath = join(vizDir, 'tbox.dot');
    const tboxMmdGenPath = join(vizDir, 'tbox.mmd');
    const tboxMmdCommittedPath = join(diagramsDir, 'tbox.mmd');
    writeFileSync(tboxDotPath, tboxDot, 'utf8');
    process.stdout.write(`wrote ${tboxDotPath}\n`);
    writeFileSync(tboxMmdGenPath, tboxMmd, 'utf8');
    process.stdout.write(`wrote ${tboxMmdGenPath}\n`);
    writeFileSync(tboxMmdCommittedPath, tboxMmd, 'utf8');
    process.stdout.write(`wrote ${tboxMmdCommittedPath}\n`);
    renderSvg(tboxDot, join(vizDir, 'tbox.svg'));
  }

  // ------------------------------------------------------------------
  // ABox
  // ------------------------------------------------------------------
  const aboxDot = emitAboxDot(bundle);
  const aboxMmd = emitAboxMmd(bundle);

  if (check) {
    const committedAbox = existsSync(join(diagramsDir, 'abox.mmd'))
      ? readFileSync(join(diagramsDir, 'abox.mmd'), 'utf8')
      : null;
    if (committedAbox !== aboxMmd) {
      process.stderr.write(
        'ontology/diagrams/abox.mmd is out of date. Run `npm run viz:ontology` to update it.\n',
      );
      process.exit(1);
    }
    process.stdout.write('ontology/diagrams/abox.mmd is up to date.\n');
  } else {
    const aboxDotPath = join(vizDir, 'abox.dot');
    const aboxMmdGenPath = join(vizDir, 'abox.mmd');
    const aboxMmdCommittedPath = join(diagramsDir, 'abox.mmd');
    writeFileSync(aboxDotPath, aboxDot, 'utf8');
    process.stdout.write(`wrote ${aboxDotPath}\n`);
    writeFileSync(aboxMmdGenPath, aboxMmd, 'utf8');
    process.stdout.write(`wrote ${aboxMmdGenPath}\n`);
    writeFileSync(aboxMmdCommittedPath, aboxMmd, 'utf8');
    process.stdout.write(`wrote ${aboxMmdCommittedPath}\n`);
    renderSvg(aboxDot, join(vizDir, 'abox.svg'));
  }

  // ------------------------------------------------------------------
  // README transclusion (uses the just-written committed .mmd files)
  // ------------------------------------------------------------------
  syncReadme(check);

  // ------------------------------------------------------------------
  // Operations graph (requires generated pipeline output)
  // ------------------------------------------------------------------
  const graphPath = join(getGraphDir(REPO_ROOT), 'operation-dependency-graph.json');
  if (existsSync(graphPath)) {
    const rawGraph: unknown = JSON.parse(readFileSync(graphPath, 'utf8'));
    if (isSerializedGraph(rawGraph)) {
      const opsDot = emitOperationsDot(rawGraph, configName);
      if (!check) {
        const opsDotPath = join(vizDir, 'operations.dot');
        writeFileSync(opsDotPath, opsDot, 'utf8');
        process.stdout.write(`wrote ${opsDotPath}\n`);
        renderSvg(opsDot, join(vizDir, 'operations.svg'));
      }
    } else {
      process.stdout.write('operations graph has unexpected shape; skipping operations.dot\n');
    }
  } else {
    process.stdout.write(
      `  (operation-dependency graph not found at ${graphPath}; skipping operations.dot)\n` +
        "  Run 'npm run extract-graph' first to generate it.\n",
    );
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  main().catch((err) => {
    process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  });
}
