/**
 * Python SDK project materialization.
 *
 * Sets up scaffolding and support files needed for an emitted Python test suite.
 * This includes package configuration, runtime helpers, and fixtures.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { EmittedFile } from '@camunda8/emitter-sdk';

/**
 * Materialize Python SDK support files into the output directory.
 * Creates Python-specific project structure, dependencies, and runtime helpers.
 */
export async function materializePythonSupport(outDir: string): Promise<void> {
  await fs.mkdir(outDir, { recursive: true });

  const scaffoldingFiles = loadPythonProjectScaffoldingFiles();

  for (const file of scaffoldingFiles) {
    const filePath = path.join(outDir, file.relativePath);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, file.content, 'utf8');
  }
}

/**
 * Load Python project scaffolding files (package.json, pyproject.toml, README, etc.).
 * These are the foundational files needed for an independent Python test project.
 */
export function loadPythonProjectScaffoldingFiles(): EmittedFile[] {
  return [
    {
      relativePath: 'pyproject.toml',
      content: `[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "camunda-sdk-tests"
version = "0.1.0"
description = "Auto-generated test suite for Camunda SDK"
requires-python = ">=3.11"
authors = [
    {name = "api-test-generator", email = "none@example.com"}
]
dependencies = [
    "camunda-orchestration-sdk>=10.0.0",
    "pytest>=7.0",
    "pytest-asyncio>=0.21",
    "httpx>=0.24",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["."]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"

[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
warn_unused_ignores = true
`,
    },
    {
      relativePath: 'README.md',
      content: `# Camunda Python SDK Tests

Auto-generated test suite for the Camunda REST API using the Python SDK.

## Setup

Install dependencies using Poetry:

\`\`\`bash
poetry install
\`\`\`

## Running Tests

Run all tests:

\`\`\`bash
poetry run pytest
\`\`\`

Run a specific test file:

\`\`\`bash
poetry run pytest test_create_widget.py -v
\`\`\`

Run with specific markers:

\`\`\`bash
poetry run pytest -m asyncio -v
\`\`\`

## Test Structure

Each test file corresponds to a single REST API endpoint. Test scenarios within each file exercise:

- **Happy path**: Standard successful request/response flow
- **Variants**: Optional response shape variations  
- **Error cases**: Expected HTTP error responses (4xx, 5xx)

## Context Variable Binding

Tests use a shared context object (\`ctx\`) to:

1. **Seed initial values** from global context seeds (e.g., tenant ID)
2. **Extract values** from response bodies to feed subsequent requests
3. **Substitute** into path parameters, query strings, and request bodies

Example:

\`\`\`python
# Seed a value before the test scenario starts
ctx.set('tenant_id_var', 'my-tenant')

# Use it in a path parameter
url = f'/process-instances/{ctx.get("tenant_id_var")}'

# Extract a value from a response and reuse it
ctx.set('process_instance_key_var', response.json()['key'])
\`\`\`

## Generated Files

- \`test_*.py\` — Individual test modules, one per REST endpoint
- \`conftest.py\` — Pytest fixtures and shared configuration
- \`support/\` — Runtime helpers and utilities
- \`fixtures/\` — Deployment artifacts (BPMN, DMN, forms)

---

Generated by [api-test-generator](https://github.com/camunda/api-test-generator)
`,
    },
    {
      relativePath: 'conftest.py',
      content: `"""
Pytest configuration and fixtures for Camunda SDK tests.
"""

import pytest
from typing import Any, Dict, AsyncGenerator
import httpx


class TestContext:
    """
    Shared test context for managing state across HTTP requests.
    
    Used to:
    - Seed initial context values (e.g., tenant ID)
    - Extract and store response values for later requests
    - Substitute variables into request bodies and path parameters
    """

    def __init__(self):
        """Initialize an empty context."""
        self.ctx: Dict[str, Any] = {}
        self.responses: Dict[str, Any] = {}

    def get(self, key: str, default: Any = None) -> Any:
        """
        Get a value from the context.
        
        Args:
            key: The context variable name
            default: Default value if key not found
            
        Returns:
            The stored value, or default if not found
        """
        return self.ctx.get(key, default)

    def set(self, key: str, value: Any) -> None:
        """
        Set a value in the context.
        
        Args:
            key: The variable name to store under
            value: The value to store
        """
        self.ctx[key] = value

    def store_response(self, operation_id: str, response: Any) -> None:
        """
        Store a response for later inspection.
        
        Args:
            operation_id: The operation that was called
            response: The response object to store
        """
        self.responses[operation_id] = response


@pytest.fixture
async def ctx() -> TestContext:
    """
    Provide a fresh test context for each test.
    
    Yields:
        A new TestContext instance with empty state
    """
    return TestContext()


@pytest.fixture
async def client() -> AsyncGenerator[httpx.AsyncClient, None]:
    """
    Provide an async HTTP client for tests.
    
    Yields:
        An httpx AsyncClient configured for the test environment
    """
    async with httpx.AsyncClient(
        base_url="http://localhost:8080/v2",
        timeout=30.0,
    ) as client:
        yield client
`,
    },
  ];
}
