/**
 * JavaScript SDK test suite emitter.
 * Lowers scenario collections into executable JavaScript/TypeScript test code
 * using the Camunda JavaScript SDK and Vitest.
 */

import type { EmitContext, EmittedFile, EmitterStrategy } from '@camunda8/emitter-sdk';
import type {
  EndpointScenario,
  EndpointScenarioCollection,
  RequestStep,
} from 'path-analyser/types';
import knownSdkMethods from './known-sdk-methods.json' with { type: 'json' };
import { renderJavaScriptBody } from './sdk-mapping.js';

// Regenerate via `npm run js-sdk:dump-methods --workspace materializer`
// whenever the @camunda8/sdk devDependency is bumped.
const KNOWN_SDK_METHODS = new Set<string>(knownSdkMethods.methods);

/**
 * Build the file name a scenario collection lowers to.
 * JavaScript test convention: `<operationId>.<mode>.test.ts`
 *
 * @example
 * 'listProcessInstances' -> 'listProcessInstances.feature.test.ts'
 */
export function jsSuiteFileName(
  collection: EndpointScenarioCollection,
  mode: 'feature' | 'integration' | 'variant' = 'feature',
): string {
  const operationId = collection.endpoint.operationId;
  return `${operationId}/${operationId}.${mode}.test.ts`;
}

/**
 * Main entry point for the JavaScript SDK emitter.
 * Creates and returns the EmitterStrategy implementation.
 *
 * Method names are resolved via `toSdkMethodName` (operationId -> real SDK
 * method name), not an upstream operation-map.json: that map's `region`
 * values are doc-example identifiers (PascalCase, sometimes multiple per
 * operationId for oneOf variants), not the SDK's actual per-operation
 * method names, so it isn't a reliable dispatch source.
 */
export function createJsSdkEmitter(): EmitterStrategy {
  return {
    id: 'js-sdk',
    name: 'JavaScript SDK',
    supportedConfigs: ['*'],
    async emit(collection: EndpointScenarioCollection, ctx: EmitContext): Promise<EmittedFile[]> {
      const content = renderJsSuite(collection, { mode: ctx.mode });
      return [
        {
          relativePath: jsSuiteFileName(collection, ctx.mode),
          content,
        },
      ];
    },
  };
}

/**
 * Render a complete JavaScript test suite for a scenario collection.
 *
 * Generates a Vitest test file with:
 * - Proper imports (vitest, @camunda8/sdk)
 * - Test context class for state management
 * - describe/it blocks for each scenario
 * - Full request/response handling for operations
 * - Assertion of HTTP status codes
 */
export function renderJsSuite(
  collection: EndpointScenarioCollection,
  opts: {
    mode?: 'feature' | 'integration' | 'variant';
  } = {},
): string {
  const lines: string[] = [];
  const mode = opts.mode ?? 'feature';
  const operationId = collection.endpoint.operationId;

  // =========================================================================
  // File header and imports
  // =========================================================================
  lines.push('/**');
  lines.push(` * Auto-generated tests for ${operationId}`);
  lines.push(' * Generated by api-test-generator');
  lines.push(' *');
  lines.push(' * Render: Vitest + Camunda JavaScript SDK');
  lines.push(' */');
  lines.push('');
  lines.push("import { describe, it, expect, beforeEach } from 'vitest';");
  lines.push("import { Camunda8 } from '@camunda8/sdk';");
  lines.push("import type { HttpSdkError } from '@camunda8/sdk';");
  lines.push('');

  // =========================================================================
  // Test context interface and setup
  // =========================================================================
  lines.push('/**');
  lines.push(' * Shared test context for managing state across requests.');
  lines.push(' * Stores scenario bindings, request/response objects, and extracted values.');
  lines.push(' */');
  lines.push('interface TestContext {');
  lines.push('  [key: string]: unknown;');
  lines.push('}');
  lines.push('');

  // =========================================================================
  // Test suite describe block
  // =========================================================================
  lines.push(`describe('${operationId} (${mode} tests)', () => {`);
  lines.push("  let client: ReturnType<Camunda8['getOrchestrationClusterApiClientLoose']>;");
  lines.push('  let ctx: TestContext;');
  lines.push('');

  lines.push('  beforeEach(() => {');
  lines.push('    // Initialize test context');
  lines.push('    ctx = {};');
  lines.push(
    '    // Zero-config: the SDK reads ZEEBE_REST_ADDRESS / CAMUNDA_AUTH_STRATEGY from env',
  );
  lines.push('    client = new Camunda8().getOrchestrationClusterApiClientLoose();');
  lines.push('  });');
  lines.push('');

  // =========================================================================
  // Render each scenario as an async it() block
  // =========================================================================
  for (const scenario of collection.scenarios) {
    renderScenarioTest(lines, scenario);
  }

  lines.push('});');
  lines.push('');

  return lines.join('\n');
}

/**
 * Render a single scenario as an async it() test block.
 *
 * For each scenario:
 * 1. Seed context from scenario.bindings
 * 2. Iterate through requestPlan operations
 * 3. Build and execute request via SDK
 * 4. Assert response status
 * 5. Store response in context for next operation
 */
function renderScenarioTest(lines: string[], scenario: EndpointScenario): void {
  const testName = `${scenario.id} - ${escapeQuotesForString(scenario.name || 'scenario')}`;
  const operations = scenario.requestPlan || [];

  // Spec/SDK version skew: some operationIds have no backing method on the
  // installed @camunda8/sdk yet (see known-sdk-methods.json). Emitting a
  // real call for these throws an opaque runtime TypeError, so skip the
  // whole scenario instead — a chain that depends on a missing step can't
  // run regardless of which step it is.
  const missingMethods = [
    ...new Set(
      operations
        .map((step) => toSdkMethodName(step.operationId))
        .filter((method) => !KNOWN_SDK_METHODS.has(method)),
    ),
  ];

  if (missingMethods.length > 0) {
    const reason = `no method ${missingMethods.map((m) => `'${m}'`).join(', ')} on installed @camunda8/sdk@${knownSdkMethods.sdkVersion} (spec/SDK version skew)`;
    lines.push('  it.skip(');
    lines.push(`    '${testName}',`);
    lines.push('    async () => {');
    lines.push(`      // SKIPPED: ${reason}`);
    lines.push('    },');
    lines.push('  );');
    lines.push('');
    return;
  }

  lines.push('  it(');
  lines.push(`    '${testName}',`);
  lines.push(`    async () => {`);

  // Seed context from scenario.bindings
  if (scenario.bindings && Object.keys(scenario.bindings).length > 0) {
    lines.push('      // Seed bindings');
    for (const [key, value] of Object.entries(scenario.bindings)) {
      if (value === '__PENDING__') {
        lines.push(`      ctx['${key}'] = undefined; // pending binding`);
      } else {
        const literal = JSON.stringify(value);
        lines.push(`      ctx['${key}'] = ${literal};`);
      }
    }
    lines.push('');
  }

  // Render each operation in the request plan
  for (let i = 0; i < operations.length; i++) {
    const step = operations[i];
    renderRequestStep(lines, step, i);
  }

  if (operations.length === 0) {
    lines.push('      // No operations in scenario');
  }

  lines.push('    },');
  lines.push('  );');
  lines.push('');
}

/**
 * Render a single request step (operation execution).
 *
 * Constructs:
 * - A single flat input object (path params + body fields merged), matching
 *   the real SDK's one-argument-per-call method signatures
 * - A `consistency` second argument for eventually-consistent reads,
 *   detected via the bound method's arity rather than a hardcoded operation
 *   list (the real SDK throws a client-side "Missing consistencyManagement
 *   parameter" error for these operations if it's omitted)
 * - Proper SDK method invocation and response assertion
 */
function renderRequestStep(lines: string[], step: RequestStep, stepIndex: number): void {
  const stepNum = stepIndex + 1;
  const opId = step.operationId;
  const method = toSdkMethodName(opId);
  const responseVar = `response${stepNum}`;
  const expectedStatus = step.expect.status;
  const isErrorExpected = expectedStatus >= 400;

  lines.push(`      // Step ${stepNum}: ${opId}`);

  // Build the request body (if any), then merge it with path params into a
  // single flat input object.
  const payloadTemplate =
    step.bodyKind === 'multipart'
      ? (step.multipartTemplate ?? step.bodyTemplate)
      : step.bodyTemplate;
  if (payloadTemplate) {
    const bodyExpr = renderJavaScriptBody(payloadTemplate, {});
    lines.push(`      const body${stepNum} = ${bodyExpr};`);
  }

  lines.push(`      const input${stepNum} = {`);
  if (payloadTemplate) {
    lines.push(`        ...body${stepNum},`);
  }
  for (const param of step.pathParams ?? []) {
    lines.push(`        ${renderObjectKey(param.name)}: ctx['${param.var}'],`);
  }
  lines.push('      };');

  // Some read operations (get-by-id, search) require an explicit consistency
  // argument as a second parameter; a plain single-arg call throws a
  // client-side error for exactly those operations. `.length` reflects the
  // bound method's declared arity at runtime, so this adapts automatically
  // as the upstream SDK adds/removes eventually-consistent operations.
  lines.push(
    `      const consistency${stepNum} = client.${method}.length >= 2 ? { consistency: { waitUpToMs: 0 } } : undefined;`,
  );
  // .bind(client) preserves the `this` binding the real SDK's generated
  // methods rely on internally (e.g. accessing `this._client`) — without
  // it, detaching the method reference from `client` before calling it
  // throws at runtime. `any` (rather than `unknown`) matches the emitted
  // code's need to chain deep, dynamically-shaped response access.
  lines.push(
    `      const call${stepNum} = client.${method}.bind(client) as (...args: unknown[]) => Promise<any>;`,
  );

  if (isErrorExpected) {
    lines.push('      try {');
    lines.push(
      `        const ${responseVar} = await call${stepNum}(input${stepNum}, consistency${stepNum});`,
    );
    lines.push(`        expect.fail('Expected ${expectedStatus} but request succeeded');`);
    lines.push('      } catch (error) {');
    lines.push('        const sdkError = error as HttpSdkError;');
    lines.push(`        expect(sdkError.status).toBe(${expectedStatus});`);
    lines.push('      }');
  } else {
    lines.push(
      `      const ${responseVar} = await call${stepNum}(input${stepNum}, consistency${stepNum});`,
    );

    if (step.extract && step.extract.length > 0) {
      for (const extract of step.extract) {
        const accessor = toOptionalAccessor(extract.fieldPath);
        lines.push(`      ctx['${extract.bind}'] = ${responseVar}${accessor};`);
      }
    }

    lines.push(`      ctx['${opId}Response'] = ${responseVar};`);
  }

  lines.push('');
}

/**
 * Convert an OpenAPI operationId to the real SDK's camelCase method name.
 * The SDK's own codegen Title-cases multi-letter acronyms before lowercasing
 * the leading character (e.g. operationId `getProcessDefinitionXML` ->
 * method `getProcessDefinitionXml`), unlike a naive camelCase pass.
 */
function toSdkMethodName(operationId: string): string {
  if (!operationId) return operationId;
  const acronymNormalized = operationId.replace(
    /[A-Z]{2,}/g,
    (run) => run.charAt(0) + run.slice(1).toLowerCase(),
  );
  return acronymNormalized.charAt(0).toLowerCase() + acronymNormalized.slice(1);
}

/**
 * Render an object literal key, quoting it only if it isn't a valid bare
 * JavaScript identifier.
 */
function renderObjectKey(name: string): string {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name) ? name : `'${name.replace(/'/g, "\\'")}'`;
}

/**
 * Escape quotes in a string for use within JavaScript string literals.
 */
function escapeQuotesForString(value: string): string {
  return value.replace(/'/g, "\\'").replace(/"/g, '\\"');
}

/**
 * Convert a string to a safe JavaScript identifier.
 * Used for test method names, variable names, etc.
 *
 * Removes special characters, replaces spaces with underscores,
 * and ensures the result is a valid identifier.
 */
function toOptionalAccessor(fieldPath: string): string {
  if (!fieldPath) return '';
  const parts = fieldPath.split('.');
  return parts
    .map((part) => {
      const match = part.match(/^([a-zA-Z_][a-zA-Z0-9_]*)(\[[0-9]+\])?$/);
      if (match) {
        const base = `?.${match[1]}`;
        const idx = match[2] ? `?.${match[2]}` : '';
        return base + idx;
      }
      return `?.['${part.replace(/'/g, "\\'")}']`;
    })
    .join('');
}
