/**
 * JavaScript SDK test suite emitter.
 * Lowers scenario collections into executable JavaScript/TypeScript test code
 * using the Camunda JavaScript SDK and Vitest.
 */

import type { EmitContext, EmittedFile, EmitterStrategy } from '@camunda8/emitter-sdk';
import type {
  EndpointScenario,
  EndpointScenarioCollection,
  RequestStep,
} from 'path-analyser/types';
import {
  buildJavaScriptUrlExpression,
  type OperationMapJsonSource,
  renderJavaScriptBody,
} from './sdk-mapping.js';

/**
 * Build the file name a scenario collection lowers to.
 * JavaScript test convention: `<operationId>.<mode>.test.ts`
 *
 * @example
 * 'listProcessInstances' -> 'listProcessInstances.feature.test.ts'
 */
export function jsSuiteFileName(
  collection: EndpointScenarioCollection,
  mode: 'feature' | 'integration' | 'variant' = 'feature',
): string {
  const operationId = collection.endpoint.operationId;
  return `${operationId}/${operationId}.${mode}.test.ts`;
}

/**
 * Main entry point for the JavaScript SDK emitter.
 * Creates and returns the EmitterStrategy implementation.
 *
 * @param operationMap Optional operation map for method resolution
 */
export function createJsSdkEmitter(
  operationMap: OperationMapJsonSource | undefined,
): EmitterStrategy {
  return {
    id: 'js-sdk',
    name: 'JavaScript SDK',
    supportedConfigs: ['*'],
    async emit(collection: EndpointScenarioCollection, ctx: EmitContext): Promise<EmittedFile[]> {
      const content = renderJsSuite(collection, {
        mode: ctx.mode,
        operationMap,
      });
      return [
        {
          relativePath: jsSuiteFileName(collection, ctx.mode),
          content,
        },
      ];
    },
  };
}

/**
 * Render a complete JavaScript test suite for a scenario collection.
 *
 * Generates a Vitest test file with:
 * - Proper imports (vitest, @camunda8/sdk)
 * - Test context class for state management
 * - describe/it blocks for each scenario
 * - Full request/response handling for operations
 * - Assertion of HTTP status codes
 */
export function renderJsSuite(
  collection: EndpointScenarioCollection,
  opts: {
    mode?: 'feature' | 'integration' | 'variant';
    operationMap?: OperationMapJsonSource;
  } = {},
): string {
  const lines: string[] = [];
  const mode = opts.mode ?? 'feature';
  const operationId = collection.endpoint.operationId;

  // =========================================================================
  // File header and imports
  // =========================================================================
  lines.push('/**');
  lines.push(` * Auto-generated tests for ${operationId}`);
  lines.push(' * Generated by api-test-generator');
  lines.push(' *');
  lines.push(' * Render: Vitest + Camunda JavaScript SDK');
  lines.push(' */');
  lines.push('');
  lines.push("import { describe, it, expect, beforeEach } from 'vitest';");
  lines.push("import { createApiClient } from '@camunda8/sdk';");
  lines.push("import type { ApiClient, RestClientError } from '@camunda8/sdk';");
  lines.push('');

  // =========================================================================
  // Test context interface and setup
  // =========================================================================
  lines.push('/**');
  lines.push(' * Shared test context for managing state across requests.');
  lines.push(' * Stores scenario bindings, request/response objects, and extracted values.');
  lines.push(' */');
  lines.push('interface TestContext {');
  lines.push('  [key: string]: unknown;');
  lines.push('}');
  lines.push('');

  // =========================================================================
  // Test suite describe block
  // =========================================================================
  lines.push(`describe('${operationId} (${mode} tests)', () => {`);
  lines.push('  let apiClient: ApiClient;');
  lines.push('  let ctx: TestContext;');
  lines.push('');

  lines.push('  beforeEach(() => {');
  lines.push('    // Initialize test context');
  lines.push('    ctx = {};');
  lines.push('    apiClient = createApiClient({');
  lines.push('      baseUrl: process.env.API_BASE_URL ?? ' + "'http://localhost:8080/v2'" + ',');
  lines.push('    });');
  lines.push('  });');
  lines.push('');

  // =========================================================================
  // Render each scenario as an async it() block
  // =========================================================================
  for (const scenario of collection.scenarios) {
    renderScenarioTest(lines, scenario, opts);
  }

  lines.push('});');
  lines.push('');

  return lines.join('\n');
}

/**
 * Render a single scenario as an async it() test block.
 *
 * For each scenario:
 * 1. Seed context from scenario.bindings
 * 2. Iterate through requestPlan operations
 * 3. Build and execute request via SDK
 * 4. Assert response status
 * 5. Store response in context for next operation
 */
function renderScenarioTest(
  lines: string[],
  scenario: EndpointScenario,
  opts: {
    mode?: 'feature' | 'integration' | 'variant';
    operationMap?: OperationMapJsonSource;
  } = {},
): void {
  const testName = `${scenario.id} - ${escapeQuotesForString(scenario.name || 'scenario')}`;

  lines.push('  it(');
  lines.push(`    '${testName}',`);
  lines.push(`    async () => {`);

  // Seed context from scenario.bindings
  if (scenario.bindings && Object.keys(scenario.bindings).length > 0) {
    lines.push('      // Seed bindings');
    for (const [key, value] of Object.entries(scenario.bindings)) {
      if (value === '__PENDING__') {
        lines.push(`      ctx['${key}'] = undefined; // pending binding`);
      } else {
        const literal = JSON.stringify(value);
        lines.push(`      ctx['${key}'] = ${literal};`);
      }
    }
    lines.push('');
  }

  // Render each operation in the request plan
  const operations = scenario.requestPlan || [];
  for (let i = 0; i < operations.length; i++) {
    const step = operations[i];
    renderRequestStep(lines, step, i, opts);
  }

  if (operations.length === 0) {
    lines.push('      // No operations in scenario');
  }

  lines.push('    },');
  lines.push('  );');
  lines.push('');
}

/**
 * Render a single request step (operation execution).
 *
 * Constructs:
 * - URL from path template with parameter substitution
 * - Request body with variable substitution
 * - Proper SDK method invocation
 * - Response assertion
 */
function renderRequestStep(
  lines: string[],
  step: RequestStep,
  stepIndex: number,
  opts: {
    mode?: 'feature' | 'integration' | 'variant';
    operationMap?: OperationMapJsonSource;
  } = {},
): void {
  const stepNum = stepIndex + 1;
  const opId = step.operationId;
  const method = opts.operationMap?.lookup(opId) ?? toCamelCase(opId);
  const responseVar = `response${stepNum}`;
  const expectedStatus = step.expect.status;
  const isErrorExpected = expectedStatus >= 400;
  const requestParts: string[] = [];

  lines.push(`      // Step ${stepNum}: ${opId}`);

  // Build URL
  if (step.pathTemplate) {
    const urlExpr = buildJavaScriptUrlExpression(step.pathTemplate, step.pathParams);
    lines.push(`      const url${stepNum} = ${urlExpr};`);
    requestParts.push(`path: url${stepNum}`);
  }

  // Build request body if present
  const payloadTemplate =
    step.bodyKind === 'multipart'
      ? (step.multipartTemplate ?? step.bodyTemplate)
      : step.bodyTemplate;
  if (payloadTemplate) {
    const bodyExpr = renderJavaScriptBody(payloadTemplate, {});
    lines.push(`      const body${stepNum} = ${bodyExpr};`);
    const payloadKey = step.bodyKind === 'multipart' ? 'multipart' : 'body';
    requestParts.push(`${payloadKey}: body${stepNum}`);
  }

  if (isErrorExpected) {
    lines.push('      try {');
    lines.push(`        const ${responseVar} = await apiClient.${method}({`);
    for (const part of requestParts) {
      lines.push(`          ${part},`);
    }
    lines.push('        });');
    lines.push(`        expect.fail('Expected ${expectedStatus} but request succeeded');`);
    lines.push('      } catch (error) {');
    lines.push(`        const restError = error as RestClientError;`);
    lines.push(`        expect(restError.status).toBe(${expectedStatus});`);
    lines.push('      }');
  } else {
    lines.push(`      const ${responseVar} = await apiClient.${method}({`);
    for (const part of requestParts) {
      lines.push(`        ${part},`);
    }
    lines.push('      });');
    lines.push(`      expect(${responseVar}.status).toBe(${expectedStatus});`);

    if (step.extract && step.extract.length > 0) {
      for (const extract of step.extract) {
        const accessor = toOptionalAccessor(extract.fieldPath);
        lines.push(`      ctx['${extract.bind}'] = ${responseVar}.data${accessor};`);
      }
    }

    lines.push(`      ctx['${opId}Response'] = ${responseVar};`);
  }

  lines.push('');
}

/**
 * Convert operationId (camelCase) to camelCase SDK method name.
 * Most SDKs use camelCase for method names.
 *
 * @example
 * 'listProcessInstances' -> 'listProcessInstances'
 * 'CreateProcessInstance' -> 'createProcessInstance'
 */
function toCamelCase(str: string): string {
  if (!str) return str;
  return str.charAt(0).toLowerCase() + str.slice(1);
}

/**
 * Escape quotes in a string for use within JavaScript string literals.
 */
function escapeQuotesForString(value: string): string {
  return value.replace(/'/g, "\\'").replace(/"/g, '\\"');
}

/**
 * Convert a string to a safe JavaScript identifier.
 * Used for test method names, variable names, etc.
 *
 * Removes special characters, replaces spaces with underscores,
 * and ensures the result is a valid identifier.
 */
function toOptionalAccessor(fieldPath: string): string {
  if (!fieldPath) return '';
  const parts = fieldPath.split('.');
  return parts
    .map((part) => {
      const match = part.match(/^([a-zA-Z_][a-zA-Z0-9_]*)(\[[0-9]+\])?$/);
      if (match) {
        const base = `?.${match[1]}`;
        const idx = match[2] ? `?.${match[2]}` : '';
        return base + idx;
      }
      return `?.['${part.replace(/'/g, "\\'")}']`;
    })
    .join('');
}
