/**
 * JavaScript SDK test suite emitter.
 * Lowers scenario collections into executable JavaScript/TypeScript test code
 * using the Camunda JavaScript SDK.
 */

import type { EmitContext, EmittedFile, EmitterStrategy } from '@camunda8/emitter-sdk';
import type { EndpointScenarioCollection } from 'path-analyser/types';
import type { OperationMapJsonSource } from './sdk-mapping.js';

/**
 * Build the file name a scenario collection lowers to.
 * JavaScript test convention: `<operationId>.feature.test.ts`
 */
export function jsSuiteFileName(
  collection: EndpointScenarioCollection,
  mode: 'feature' | 'integration' | 'variant' = 'feature',
): string {
  const operationId = collection.endpoint.operationId;
  return `${operationId}/${operationId}.${mode}.test.ts`;
}

/**
 * Main entry point for the JavaScript SDK emitter.
 * Creates and returns the EmitterStrategy implementation.
 *
 * @param operationMap Optional operation map for method resolution
 */
export function createJsSdkEmitter(operationMap: OperationMapJsonSource | undefined): EmitterStrategy {
  return {
    id: 'js-sdk',
    name: 'JavaScript SDK',
    supportedConfigs: ['*'],
    async emit(
      collection: EndpointScenarioCollection,
      ctx: EmitContext,
    ): Promise<EmittedFile[]> {
      const content = renderJsSuite(collection, {
        mode: ctx.mode,
        operationMap,
      });
      return [
        {
          relativePath: jsSuiteFileName(collection, ctx.mode),
          content,
        },
      ];
    },
  };
}

/**
 * Render a complete JavaScript test suite for a scenario collection.
 */
export function renderJsSuite(
  collection: EndpointScenarioCollection,
  opts: {
    mode?: 'feature' | 'integration' | 'variant';
    operationMap?: OperationMapJsonSource;
  } = {},
): string {
  const lines: string[] = [];
  const operationId = collection.endpoint.operationId;
  const mode = opts.mode ?? 'feature';

  // File header
  lines.push('/**');
  lines.push(` * Auto-generated tests for ${operationId}`);
  lines.push(` * Generated by api-test-generator`);
  lines.push(' */');
  lines.push('');

  // Imports
  lines.push("import { describe, it, expect, beforeEach } from 'vitest';");
  lines.push("import type { RestClient } from '@camunda8/sdk';");
  lines.push('');

  // Test suite
  lines.push(`describe('${operationId} - ${mode} tests', () => {`);
  lines.push('  let ctx: Record<string, unknown>;');
  lines.push('');
  lines.push('  beforeEach(() => {');
  lines.push('    ctx = {};');
  lines.push('  });');
  lines.push('');

  // Scenarios
  for (const scenario of collection.scenarios) {
    lines.push(`  it('${scenario.id} - ${scenario.name || 'scenario'}', async () => {`);
    lines.push('    // TODO: Implement scenario');
    lines.push('    expect(true).toBe(true);');
    lines.push('  });');
    lines.push('');
  }

  lines.push('});');
  lines.push('');

  return lines.join('\n');
}
